### ISSUE TITLE
Install failing on latest

### ISSUE THREAD

**Issue by ericelliott** [elementalui/elemental#109]
```sh
[20:07:23] Using gulpfile ~/Dropbox/dev/universal-keystone/node_modules/elemental/gulpfile.js
[20:07:23] Starting 'build:lib'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
ReferenceError: [BABEL] /Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/src/Elemental.js: Unknown option: /Users/eric/Dropbox/dev/universal-keystone/.babelrc.presets
    at Logger.error (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at DestroyableTransform._transform (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/gulp-babel/index.js:30:20)
    at DestroyableTransform.Transform._read (/Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/node_modules/readable-stream/lib/_stream_transform.js:172:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/eric/.nvm/versions/node/v4.2.2/bin/node" "/Users/eric/.nvm/versions/node/v4.2.2/bin/npm" "run" "build:lib"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE
npm ERR! elemental@0.5.8 build:lib: `gulp build:lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elemental@0.5.8 build:lib script 'gulp build:lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elemental package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build:lib
npm ERR! You can get their info via:
npm ERR!     npm owner ls elemental
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eric/Dropbox/dev/universal-keystone/node_modules/elemental/npm-debug.log
```

**Comment by JedWatson** [comment]
I can't reproduce this from within Elemental itself.

Babel is traversing up and finding `/Users/eric/Dropbox/dev/universal-keystone/.babelrc.presets` and then choking on that. We need to tell it not to in Elemental somehow. @sebmck any hints on how to do this?

**Comment by ericelliott** [comment]
Oh, if that's all it is, maybe it's not as big a deal as I thought. If the tests are passing for you, could you publish the latest so I can just `npm install` as usual and test it out?

**Comment by ericelliott** [comment]
I think upgrading this to Babel 6 is probably the best way forward?
